# configs/eval_config_vllm.yaml - vLLM批量推理评估配置文件
# =============================================================================

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          🏃 运行环境配置                               │
# └─────────────────────────────────────────────────────────────────────────┘
run:
  cuda_visible_devices: null         # GPU设备ID (null为使用所有可用GPU)
  seed: 42                           # 随机种子，确保可重现性

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          🤖 模型配置                                   │
# └─────────────────────────────────────────────────────────────────────────┘
model:
  model_id: "Qwen/Qwen2.5-VL-3B-Instruct"              # vLLM支持的模型ID
  load_in_4bit: false                                   # vLLM不使用4bit量化

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          📊 数据配置                                   │
# └─────────────────────────────────────────────────────────────────────────┘
data:
  num_samples: 50                    # 评估样本数量 (vLLM适合批量处理更多样本)
  dataset_name: "Litian2002/spatialvlm_qa"  # 数据集名称
  dataset_split: "train"             # 数据集分割

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          🎛️ 生成配置                                   │
# └─────────────────────────────────────────────────────────────────────────┘
generation:
  max_new_tokens: 256               # 生成的最大token数
  temperature: 0.1                  # 生成温度
  do_sample: true                   # 是否采样（vLLM中通过temperature控制）
  use_cache: true                   # 是否使用缓存

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          📏 评估指标配置                               │
# └─────────────────────────────────────────────────────────────────────────┘
metrics:
  # 文本一致性权重设置
  text_consistency:
    sequence_weight: 0.4            # 序列匹配权重
    jaccard_weight: 0.4             # 词汇重叠权重
    boolean_weight: 0.2             # 布尔匹配权重
  
  # 数值型问题评分策略
  numerical_scoring:
    perfect_match: 1.0              # 完美匹配 (0%误差)
    excellent: 0.95                 # 优秀 (≤1%误差)
    very_good: 0.90                 # 很好 (≤5%误差)
    good: 0.80                      # 良好 (≤10%误差)
    acceptable: 0.70                # 可接受 (≤20%误差)
    poor: 0.50                      # 较差 (≤50%误差)
    very_poor: 0.20                 # 很差 (>50%误差)
  
  # 综合评分权重
  score_weights:
    numerical_precision: 0.7        # 数值型问题中数值精度权重
    text_consistency: 0.3           # 数值型问题中文本一致性权重
    no_numerical_penalty: 0.5       # 数值型问题但无数值回答时的降权系数

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          💾 输出配置                                   │
# └─────────────────────────────────────────────────────────────────────────┘
output:
  base_output_dir: "eval_results_vllm"                # 基础输出目录
  csv_filename: "evaluation_results_vllm.csv"         # CSV输出文件名
  visualization_dir: "charts"                          # 可视化输出子目录
  samples_dir: "samples"                               # 样本保存子目录
  reports_dir: "reports"                               # 报告保存子目录
  create_detailed_report: true                         # 是否创建详细报告

# ┌─────────────────────────────────────────────────────────────────────────┐
# │                          🎨 可视化配置                                 │
# └─────────────────────────────────────────────────────────────────────────┘
visualization:
  figure_size: [12, 8]              # 图表尺寸
  dpi: 300                          # 图表分辨率
  style: "seaborn-v0_8"             # 图表样式
  font_size: 12                     # 字体大小
  colors:
    primary: "#4CAF50"              # 主要颜色（绿色）
    secondary: "#2196F3"            # 次要颜色（蓝色）
    accent: "#FF9800"               # 强调颜色（橙色）
    error: "#F44336"                # 错误颜色（红色）
    background: "white"             # 背景颜色 